/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hugo.yml.corrector;

import org.junit.Ignore;
import org.junit.Test;

public class AppTest {
    @Ignore
    @Test
    public void testAppHasAGreeting() {
    }
}
